name: Test
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile && \
          yarn --cwd ./examples/client install --frozen-lockfile && \
          yarn --cwd ./examples/manager install --frozen-lockfile && \
          yarn --cwd ./examples/react-libs install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
